"""empty message

Revision ID: de7addf9a009
Revises: 5e344240df20
Create Date: 2023-07-06 22:56:15.011369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de7addf9a009'
down_revision = '5e344240df20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('composition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=1000), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('composition', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_composition_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('composition', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_composition_timestamp'))

    op.drop_table('composition')
    # ### end Alembic commands ###
